"""Popular Malaysia destination name fragments for featured prefetch."""

from __future__ import annotations

# Prefer specific landmark names. Short/broad tokens (e.g. "Ipoh") over-match.
# Matched case-insensitively as substring against destination_name.
FEATURED_DESTINATION_NAMES: list[str] = [
    "Petronas Twin Towers",
    "Suria KLCC",
    "Aquaria KLCC",
    "Batu Caves",
    "Dataran Merdeka",
    "Merdeka Square",
    "Petaling Street",
    "Central Market Kuala Lumpur",
    "Thean Hou Temple",
    "Menara Kuala Lumpur",
    "KL Tower",
    "Titiwangsa Lake",
    "Islamic Arts Museum",
    "The National Museum of Malaysia",
    "National Museum",
    "Mid Valley Megamall",
    "Pavilion Kuala Lumpur",
    "Sunway Pyramid",
    "Sunway Lagoon",
    "Genting SkyWorlds",
    "Genting Highlands Premium Outlets",
    "BOH Tea Centre",
    "BOH Tea Plantation",
    "Penang Hill",
    "Kek Lok Si",
    "Fort Cornwallis",
    "Batu Ferringhi Beach",
    "Entopia by Penang Butterfly",
    "Tropical Spice Garden",
    "Jonker Walk",
    "Jonker Street",
    "A Famosa",
    "Stadthuys",
    "Dutch Square",
    "Melaka River Cruise",
    "Langkawi Cable Car",
    "Underwater World Langkawi",
    "Kilim Karst",
    "Eagle Square",
    "Mount Kinabalu",
    "Kinabalu Park",
    "Sepilok Orangutan",
    "Tunku Abdul Rahman Marine Park",
    "Gaya Street Sunday Market",
    "Mari Mari Cultural Village",
    "Tip of Borneo",
    "Kuching Waterfront",
    "Sarawak Cultural Village",
    "Bako National Park",
    "Semenggoh Nature Reserve",
    "Taman Negara National Park",
    "Gua Tempurung",
    "Kellie's Castle",
    "Lost World of Tambun",
    "LEGOLAND Malaysia",
    "Sultan Abu Bakar State Mosque",
    "Putrajaya Botanical Garden",
    "Taman Botani Putrajaya",
    "Kuala Lumpur Bird Park",
    "Putra Mosque",
    "Masjid Putra",
    "AEON Mall Kuching",
    "1 Utama Shopping Centre",
    "Queensbay Mall",
    "Gurney Plaza",
    "The Spring Shopping Mall Kuching",
    "Imago Shopping Mall",
    "Perdana Botanical",
    "Zoo Negara",
]


def matches_featured_name(name: str) -> bool:
    """True if destination_name contains a curated featured fragment."""
    hay = (name or "").casefold()
    if not hay:
        return False
    return any(fragment.casefold() in hay for fragment in FEATURED_DESTINATION_NAMES)
